name = "Forgive"
version = "0.1.0"
defaultTargets = ["Forgive", "forgive"]

[[require]]
name = "Cli"
scope = "leanprover"
version = "git#v4.35.0-rc2"

[[lean_lib]]
name = "Forgive"

[[lean_exe]]
name = "forgive"
root = "Main"
supportInterpreter = true
